### ISSUE TITLE
UTC Missing sets and record number discrepancies 

### ISSUE THREAD

**Issue by markpbaggett** [utkdigitalinitiatives/DLTN#7]
# Report an Issue

## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform

## New Set(s) / Reingest Existing Set

* p16877coll1
* p16877coll2
* p16877coll3

## Problem with Set or Transform

The above sets are missing.  Also, as reported by Carolyn Runyon, there are several hundred records missing. Add those sets and report records associated with each set.  Also, create lists of records in each set and report back.

**Comment by markpbaggett** [comment]
Adding @carolynfrunyon.

**Comment by carolynfrunyon** [comment]
I like your issue template text, Mark. If you're thinking we could use this instead of the E[xisting Partner Repository Update form ](http://surveys7.membershipsoftware.org/ts/TakeSurvey.asp?PageNumber=1&SurveyID=51M683LL5726M) on the Tenn-Share site, I'm on board!

**Comment by carolynfrunyon** [comment]
The total item count is 3284. I bet you only need to re-harvest p16877coll14, but it can't hurt to re-harvest everything, can it?

**Comment by markpbaggett** [comment]
It would only hurt if one of the records was missing a required element. Here are the numbers I'm seeing (not counting deleted's) from http://cdm16877.contentdm.oclc.org/oai/oai.php:

1. coll1 - 71 (same as repox)
2. coll2 - 7 (same as repox)
3. coll3 - 63 (same as repox)
4. coll4 - 17 (same as repox)
5. coll5 - 20 (same as repox)
6. coll6 - 72 (**Repox shows 66**)
7. coll7 - 70 (same as repox)
8. coll8 - 196 (same as repox)
9. coll9 - 2026 (same as repox)
10. coll10 - 90 (same as repox)
11. coll11 - 49 (same as repox)
12. coll12 - 65 (same as repox)
13. coll13 - 18 (same as repox)
14. coll14 - 305 (same as repox)
15. coll15 - 102 (**Repox shows 58**)
16. coll16 - 4 (same as repox)
17. coll17 - 12 (same as repox)
18. coll18 - 4 (same as repox)
19. coll19 - 29 (same as repox)
20. coll20 - 5 (same as repox)
21. coll21 - 59 (same as repox)

I'm happy to reharvest those 2 sets, but I'm not sure about those other 5 records.  My script doesn't see it in your feed. Any idea which it might be?

**Comment by carolynfrunyon** [comment]
None of our sets are missing required metadata. I reckon you could re-harvest the lot without trouble.

**Comment by markpbaggett** [comment]
Done reharvesting, but Repox only grabbed 3279 as well.  The numbers in Repox now match the above.  Any idea which set is showing the discrepancy? Coll14 only shows 304.  If you have individual set numbers (per set), I may be able to figure out what is different.

**Comment by carolynfrunyon** [comment]
I'm finding the same discrepancies as you are. Not sure why. In CONTENTdm, there's no way to prevent individual items in a set from being harvested, for example.

[CDM Item Counts.xlsx](https://github.com/utkdigitalinitiatives/DLTN/files/849066/CDM.Item.Counts.xlsx)

**Comment by markpbaggett** [comment]
What were you using that showed the other numbers? 

Are you good with closing the issue, or do you want to keep open until we figure out what is causing this discrepancy?

**Comment by carolynfrunyon** [comment]
I just pulled them from the CDM backend, but I've gotten the same figure querying the OAI feed with Christina's metadataQA scripts.

**Comment by markpbaggett** [comment]
Hmmm. Isn't there a process that publishes ContentDM items to the OAI-PMH provider?  Could it be that there are some things that need to be published.

I know you said that Christina's scripts show this.  Those scripts are great, but I've seen some strange things with those (remember the TSLA rights statements getting split into separate fields even though they were in one XML node?).  

Let me know what we need to do to resolve this issue.

**Comment by carolynfrunyon** [comment]
There is, but the CDM process works set by set, not item by item. That's why I'm confused.

To me, it looks like the discrepancy is the Repox, based on your earlier analysis (copied below). The way I'm reading this is that Repox is showing 6 fewer items in coll6 than you are pulling from the OAI feed. Is that right?
coll1 - 71 (same as repox)
coll2 - 7 (same as repox)
coll3 - 63 (same as repox)
coll4 - 17 (same as repox)
coll5 - 20 (same as repox)
coll6 - 72 (Repox shows 66)
coll7 - 70 (same as repox)
coll8 - 196 (same as repox)
coll9 - 2026 (same as repox)
coll10 - 90 (same as repox)
coll11 - 49 (same as repox)
coll12 - 65 (same as repox)
coll13 - 18 (same as repox)
coll14 - 305 (same as repox)
coll15 - 102 (Repox shows 58)
coll16 - 4 (same as repox)
coll17 - 12 (same as repox)
coll18 - 4 (same as repox)
coll19 - 29 (same as repox)
coll20 - 5 (same as repox)
coll21 - 59 (same as repox)

**Comment by markpbaggett** [comment]
Nope, not anymore.  I reingested everything in Repox and it matches what my tool says from the OAI feed.

**Comment by markpbaggett** [comment]
In other words, coll6 and coll15 had new items since last March.

**Comment by carolynfrunyon** [comment]
So, the total item count you have is?

**Comment by markpbaggett** [comment]
3284 -- both my tool from your feed and the number in Repox.

**Comment by carolynfrunyon** [comment]
Got it! We're on the same page. Yes, the total item count on my end and yours are both 3284, so you can close this ticket. You've got everything!
