### ISSUE TITLE
dataProvider Issue on MTSU Set p15838coll3

### ISSUE THREAD

**Issue by markpbaggett** [utkdigitalinitiatives/DLTN#8]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform

In DPLA MAP 4, .dataProvider and is a required element.  The existing xsl transform for p15838coll3 expects there to be at least 1 dc:publisher, and it maps to recordInfo/recordContentSource (which in turn is transformed to .dataProvider).  

To fix this, I propose:

1. Add a conditional:
    - If there are no dc:publishers, write: <recordInfo><recordContentSource>Digital Initiatives, James E. Walker Library, Middle Tennessee State University<recordInfo><recordContentSource>

**Comment by markpbaggett** [comment]
This is also an issue in p15838coll7.  No publishers or contributors.

That being said, since the change is happening to mtsuDCtoMODS.xsl, this should be fixed with the above proposed change.

**Comment by CanOfBees** [comment]
Closing.
